"""design variants, owner token, zone box, variant-scoped data

Revision ID: 142421393833
Revises: 9849767aecd9
Create Date: 2026-06-17 00:53:05.604555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142421393833'
down_revision: Union[str, None] = '657bbaee4555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project_estimations', sa.Column('variant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'project_estimations', 'design_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.add_column('project_images', sa.Column('variant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'project_images', 'design_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('owner_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_projects_owner_token'), 'projects', ['owner_token'], unique=False)
    op.add_column('zone_material_assignments', sa.Column('variant_id', sa.UUID(), nullable=True))
    op.drop_constraint('zone_material_assignments_zone_id_key', 'zone_material_assignments', type_='unique')
    op.create_unique_constraint('uq_variant_zone', 'zone_material_assignments', ['variant_id', 'zone_id'])
    op.create_foreign_key(None, 'zone_material_assignments', 'design_variants', ['variant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zone_material_assignments', type_='foreignkey')
    op.drop_constraint('uq_variant_zone', 'zone_material_assignments', type_='unique')
    op.create_unique_constraint('zone_material_assignments_zone_id_key', 'zone_material_assignments', ['zone_id'])
    op.drop_column('zone_material_assignments', 'variant_id')
    op.drop_index(op.f('ix_projects_owner_token'), table_name='projects')
    op.drop_column('projects', 'owner_token')
    op.drop_constraint(None, 'project_images', type_='foreignkey')
    op.drop_column('project_images', 'variant_id')
    op.drop_constraint(None, 'project_estimations', type_='foreignkey')
    op.drop_column('project_estimations', 'variant_id')
    op.drop_table('design_variants')
    # ### end Alembic commands ###
