"""sync schema drift

Revision ID: 9849767aecd9
Revises: 657bbaee4555
Create Date: 2026-06-16 22:58:51.665572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9849767aecd9'
down_revision: Union[str, None] = '657bbaee4555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_estimations', sa.Column('dimension_anchor_used', sa.String(length=64), nullable=True))
    op.add_column('project_estimations', sa.Column('dimension_confidence', sa.Float(), nullable=True))
    op.add_column('project_estimations', sa.Column('dimension_reasoning', sa.Text(), nullable=True))
    op.add_column('project_zones', sa.Column('box_2d', sa.JSON(), nullable=True))
    op.drop_column('project_zones', 'dimension_source')
    op.drop_column('project_zones', 'box')
    op.drop_column('project_zones', 'measured_width_ft')
    op.drop_column('project_zones', 'measured_height_ft')
    op.add_column('projects', sa.Column('renovation_suggestions', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('style_hint', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('dimension_hints', sa.JSON(), nullable=True))
    op.drop_column('projects', 'design_suggestions')
    op.drop_column('projects', 'dimension_method')
    op.drop_column('projects', 'condition_summary')
    op.drop_column('projects', 'dimension_confidence')
    op.drop_column('projects', 'dimension_reference')
    op.drop_column('projects', 'overall_style')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('overall_style', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('dimension_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('dimension_confidence', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('condition_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('dimension_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('design_suggestions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('projects', 'dimension_hints')
    op.drop_column('projects', 'style_hint')
    op.drop_column('projects', 'renovation_suggestions')
    op.add_column('project_zones', sa.Column('measured_height_ft', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('project_zones', sa.Column('measured_width_ft', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('project_zones', sa.Column('box', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('project_zones', sa.Column('dimension_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('project_zones', 'box_2d')
    op.drop_column('project_estimations', 'dimension_reasoning')
    op.drop_column('project_estimations', 'dimension_confidence')
    op.drop_column('project_estimations', 'dimension_anchor_used')
    # ### end Alembic commands ###
